name: Deploy dev

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BACKEND: ${{ secrets.DEV_BACKEND }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.DEV_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
          envkey_STRIPE_SIGNING_SECRET: ${{ secrets.DEV_STRIPE_SIGNING_SECRET }}
          envkey_NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.DEV_NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
          envkey_PAYPAL_SECRET: ${{ secrets.DEV_PAYPAL_SECRET }}
          envkey_PAYPAL_WEBHOOK_ID: ${{ secrets.DEV_PAYPAL_WEBHOOK_ID }}
          envkey_PAYPAL_API_URL: ${{ secrets.DEV_PAYPAL_WEBHOOK_ID }}
          # Woocommerce
          envkey_WC_CONSUMER_KEY: ${{ secrets.DEV_WC_CONSUMER_KEY }}
          envkey_WC_CONSUMER_SECRET: ${{ secrets.DEV_WC_CONSUMER_SECRET }}
          envkey_NEXT_PUBLIC_WORDPRESS_URL: ${{ secrets.DEV_NEXT_PUBLIC_WORDPRESS_URL }}
          # envkey_NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/vkluchenkov/bestpicture:latest-dev .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/vkluchenkov/bestpicture:latest-dev

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/vkluchenkov/bestpicture:latest-dev
            docker stop bestpicture-dev
            docker rm bestpicture-dev
            docker run -d -p 49166:3000 --name=bestpicture-dev --restart=always --pull=always ghcr.io/vkluchenkov/bestpicture:latest-dev
            docker system prune -f
